services:
  footballstatsapi:
    image: footballstatsapi
    build:
      context: .
      dockerfile: FootBallStatsApi/Dockerfile

  footballapi:
    image: footballapi
    build:
      context: .
      dockerfile: FootballApi/Dockerfile
